// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCICFx6S8eUkMlGE4OyodSE9MznDUbFttk',
    appId: '1:598522706420:web:2b786861e1497594ee21a1',
    messagingSenderId: '598522706420',
    projectId: 'swift-feed',
    authDomain: 'swift-feed.firebaseapp.com',
    storageBucket: 'swift-feed.appspot.com',
    measurementId: 'G-C8900Q2XBF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJQNpG3wH0r4L4zjUoixQa0-FXBlcF10E',
    appId: '1:598522706420:android:232bc039c5023fc4ee21a1',
    messagingSenderId: '598522706420',
    projectId: 'swift-feed',
    storageBucket: 'swift-feed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3I3E-LduqFJuHfhEJavpJbGOTpOJP_wc',
    appId: '1:598522706420:ios:5a2dcdf84cedea3cee21a1',
    messagingSenderId: '598522706420',
    projectId: 'swift-feed',
    storageBucket: 'swift-feed.appspot.com',
    iosClientId: '598522706420-fu4lsso3h44fkjd61ki9nvdvqr4ogqi5.apps.googleusercontent.com',
    iosBundleId: 'com.swiftfeed.swiftfeed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3I3E-LduqFJuHfhEJavpJbGOTpOJP_wc',
    appId: '1:598522706420:ios:d54c778df1e8a511ee21a1',
    messagingSenderId: '598522706420',
    projectId: 'swift-feed',
    storageBucket: 'swift-feed.appspot.com',
    iosClientId: '598522706420-l75jhpojfnn5ur2j87uekmm89ei12qqn.apps.googleusercontent.com',
    iosBundleId: 'com.swiftfeed.swiftfeed.RunnerTests',
  );
}
